/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminMailRouteImport } from './routes/admin/mail'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as ProtectedSendTestRouteImport } from './routes/_protected/send-test'
import { Route as ProtectedMailboxesRouteImport } from './routes/_protected/mailboxes'
import { Route as ProtectedInboxRouteImport } from './routes/_protected/inbox'
import { Route as ProtectedEmailsRouteImport } from './routes/_protected/emails'
import { Route as ProtectedDomainsRouteImport } from './routes/_protected/domains'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected/api-keys'
import { Route as ProtectedAccountRouteImport } from './routes/_protected/account'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminRolesRoleIdRouteImport } from './routes/admin/roles/$roleId'
import { Route as ProtectedInboxEmailIdRouteImport } from './routes/_protected/inbox/$emailId'
import { Route as ProtectedEmailsEmailIdRouteImport } from './routes/_protected/emails/$emailId'
import { Route as ProtectedDomainsDomainIdRouteImport } from './routes/_protected/domains/$domainId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailRoute = AdminMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ProtectedSendTestRoute = ProtectedSendTestRouteImport.update({
  id: '/send-test',
  path: '/send-test',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMailboxesRoute = ProtectedMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInboxRoute = ProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEmailsRoute = ProtectedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDomainsRoute = ProtectedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoleIdRoute = AdminRolesRoleIdRouteImport.update({
  id: '/$roleId',
  path: '/$roleId',
  getParentRoute: () => AdminRolesRoute,
} as any)
const ProtectedInboxEmailIdRoute = ProtectedInboxEmailIdRouteImport.update({
  id: '/$emailId',
  path: '/$emailId',
  getParentRoute: () => ProtectedInboxRoute,
} as any)
const ProtectedEmailsEmailIdRoute = ProtectedEmailsEmailIdRouteImport.update({
  id: '/$emailId',
  path: '/$emailId',
  getParentRoute: () => ProtectedEmailsRoute,
} as any)
const ProtectedDomainsDomainIdRoute =
  ProtectedDomainsDomainIdRouteImport.update({
    id: '/$domainId',
    path: '/$domainId',
    getParentRoute: () => ProtectedDomainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof ProtectedAccountRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/domains': typeof ProtectedDomainsRouteWithChildren
  '/emails': typeof ProtectedEmailsRouteWithChildren
  '/inbox': typeof ProtectedInboxRouteWithChildren
  '/mailboxes': typeof ProtectedMailboxesRoute
  '/send-test': typeof ProtectedSendTestRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/domains/$domainId': typeof ProtectedDomainsDomainIdRoute
  '/emails/$emailId': typeof ProtectedEmailsEmailIdRoute
  '/inbox/$emailId': typeof ProtectedInboxEmailIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/account': typeof ProtectedAccountRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/domains': typeof ProtectedDomainsRouteWithChildren
  '/emails': typeof ProtectedEmailsRouteWithChildren
  '/inbox': typeof ProtectedInboxRouteWithChildren
  '/mailboxes': typeof ProtectedMailboxesRoute
  '/send-test': typeof ProtectedSendTestRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/domains/$domainId': typeof ProtectedDomainsDomainIdRoute
  '/emails/$emailId': typeof ProtectedEmailsEmailIdRoute
  '/inbox/$emailId': typeof ProtectedInboxEmailIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/setup': typeof SetupRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/domains': typeof ProtectedDomainsRouteWithChildren
  '/_protected/emails': typeof ProtectedEmailsRouteWithChildren
  '/_protected/inbox': typeof ProtectedInboxRouteWithChildren
  '/_protected/mailboxes': typeof ProtectedMailboxesRoute
  '/_protected/send-test': typeof ProtectedSendTestRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/mail': typeof AdminMailRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/roles': typeof AdminRolesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_protected/domains/$domainId': typeof ProtectedDomainsDomainIdRoute
  '/_protected/emails/$emailId': typeof ProtectedEmailsEmailIdRoute
  '/_protected/inbox/$emailId': typeof ProtectedInboxEmailIdRoute
  '/admin/roles/$roleId': typeof AdminRolesRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/onboarding'
    | '/setup'
    | '/login'
    | '/signup'
    | '/account'
    | '/api-keys'
    | '/dashboard'
    | '/domains'
    | '/emails'
    | '/inbox'
    | '/mailboxes'
    | '/send-test'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/mail'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/payment/success'
    | '/admin/'
    | '/domains/$domainId'
    | '/emails/$emailId'
    | '/inbox/$emailId'
    | '/admin/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/onboarding'
    | '/setup'
    | '/login'
    | '/signup'
    | '/account'
    | '/api-keys'
    | '/dashboard'
    | '/domains'
    | '/emails'
    | '/inbox'
    | '/mailboxes'
    | '/send-test'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/mail'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/payment/success'
    | '/admin'
    | '/domains/$domainId'
    | '/emails/$emailId'
    | '/inbox/$emailId'
    | '/admin/roles/$roleId'
  id:
    | '__root__'
    | '/_protected'
    | '/accept-invitation'
    | '/admin'
    | '/onboarding'
    | '/setup'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_protected/account'
    | '/_protected/api-keys'
    | '/_protected/dashboard'
    | '/_protected/domains'
    | '/_protected/emails'
    | '/_protected/inbox'
    | '/_protected/mailboxes'
    | '/_protected/send-test'
    | '/admin/activity'
    | '/admin/feedback'
    | '/admin/mail'
    | '/admin/overview'
    | '/admin/rate-limits'
    | '/admin/roles'
    | '/admin/users'
    | '/admin/visitors'
    | '/admin/webhooks'
    | '/payment/success'
    | '/_public/'
    | '/admin/'
    | '/_protected/domains/$domainId'
    | '/_protected/emails/$emailId'
    | '/_protected/inbox/$emailId'
    | '/admin/roles/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SetupRoute: typeof SetupRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail': {
      id: '/admin/mail'
      path: '/mail'
      fullPath: '/admin/mail'
      preLoaderRoute: typeof AdminMailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_protected/send-test': {
      id: '/_protected/send-test'
      path: '/send-test'
      fullPath: '/send-test'
      preLoaderRoute: typeof ProtectedSendTestRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/mailboxes': {
      id: '/_protected/mailboxes'
      path: '/mailboxes'
      fullPath: '/mailboxes'
      preLoaderRoute: typeof ProtectedMailboxesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox': {
      id: '/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ProtectedInboxRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/emails': {
      id: '/_protected/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof ProtectedEmailsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/domains': {
      id: '/_protected/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof ProtectedDomainsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/$roleId': {
      id: '/admin/roles/$roleId'
      path: '/$roleId'
      fullPath: '/admin/roles/$roleId'
      preLoaderRoute: typeof AdminRolesRoleIdRouteImport
      parentRoute: typeof AdminRolesRoute
    }
    '/_protected/inbox/$emailId': {
      id: '/_protected/inbox/$emailId'
      path: '/$emailId'
      fullPath: '/inbox/$emailId'
      preLoaderRoute: typeof ProtectedInboxEmailIdRouteImport
      parentRoute: typeof ProtectedInboxRoute
    }
    '/_protected/emails/$emailId': {
      id: '/_protected/emails/$emailId'
      path: '/$emailId'
      fullPath: '/emails/$emailId'
      preLoaderRoute: typeof ProtectedEmailsEmailIdRouteImport
      parentRoute: typeof ProtectedEmailsRoute
    }
    '/_protected/domains/$domainId': {
      id: '/_protected/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof ProtectedDomainsDomainIdRouteImport
      parentRoute: typeof ProtectedDomainsRoute
    }
  }
}

interface ProtectedDomainsRouteChildren {
  ProtectedDomainsDomainIdRoute: typeof ProtectedDomainsDomainIdRoute
}

const ProtectedDomainsRouteChildren: ProtectedDomainsRouteChildren = {
  ProtectedDomainsDomainIdRoute: ProtectedDomainsDomainIdRoute,
}

const ProtectedDomainsRouteWithChildren =
  ProtectedDomainsRoute._addFileChildren(ProtectedDomainsRouteChildren)

interface ProtectedEmailsRouteChildren {
  ProtectedEmailsEmailIdRoute: typeof ProtectedEmailsEmailIdRoute
}

const ProtectedEmailsRouteChildren: ProtectedEmailsRouteChildren = {
  ProtectedEmailsEmailIdRoute: ProtectedEmailsEmailIdRoute,
}

const ProtectedEmailsRouteWithChildren = ProtectedEmailsRoute._addFileChildren(
  ProtectedEmailsRouteChildren,
)

interface ProtectedInboxRouteChildren {
  ProtectedInboxEmailIdRoute: typeof ProtectedInboxEmailIdRoute
}

const ProtectedInboxRouteChildren: ProtectedInboxRouteChildren = {
  ProtectedInboxEmailIdRoute: ProtectedInboxEmailIdRoute,
}

const ProtectedInboxRouteWithChildren = ProtectedInboxRoute._addFileChildren(
  ProtectedInboxRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDomainsRoute: typeof ProtectedDomainsRouteWithChildren
  ProtectedEmailsRoute: typeof ProtectedEmailsRouteWithChildren
  ProtectedInboxRoute: typeof ProtectedInboxRouteWithChildren
  ProtectedMailboxesRoute: typeof ProtectedMailboxesRoute
  ProtectedSendTestRoute: typeof ProtectedSendTestRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDomainsRoute: ProtectedDomainsRouteWithChildren,
  ProtectedEmailsRoute: ProtectedEmailsRouteWithChildren,
  ProtectedInboxRoute: ProtectedInboxRouteWithChildren,
  ProtectedMailboxesRoute: ProtectedMailboxesRoute,
  ProtectedSendTestRoute: ProtectedSendTestRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface AdminRolesRouteChildren {
  AdminRolesRoleIdRoute: typeof AdminRolesRoleIdRoute
}

const AdminRolesRouteChildren: AdminRolesRouteChildren = {
  AdminRolesRoleIdRoute: AdminRolesRoleIdRoute,
}

const AdminRolesRouteWithChildren = AdminRolesRoute._addFileChildren(
  AdminRolesRouteChildren,
)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminMailRoute: typeof AdminMailRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminRolesRoute: typeof AdminRolesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminMailRoute: AdminMailRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminRolesRoute: AdminRolesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SetupRoute: SetupRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
