#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DOMAIN="${DOMAIN:-}"
MAIL_HOST="${MAIL_HOST:-}"
POSTMASTER="${POSTMASTER:-postmaster}"
ROOT="${ROOT:-/opt/mailu}"
VERSION="${VERSION:-2024.06}"
SUBNET="${SUBNET:-192.168.203.0/24}"
BIND_ADDRESS4="${BIND_ADDRESS4:-0.0.0.0}"
TLS_FLAVOR="${TLS_FLAVOR:-letsencrypt}"
AUTH_RATELIMIT="${AUTH_RATELIMIT:-10/minute}"
MESSAGE_RATELIMIT="${MESSAGE_RATELIMIT:-200/day}"
MAILU_ENV="${MAILU_ENV:-$ROOT_DIR/deploy/mailu.env}"
MAILU_COMPOSE="${MAILU_COMPOSE:-$ROOT_DIR/docker.maulu-setup.yml}"
MAILU_ADMIN_PASSWORD="${MAILU_ADMIN_PASSWORD:-}"
MAILBOX_SECRET_KEY="${MAILBOX_SECRET_KEY:-}"
DRY_RUN="${DRY_RUN:-false}"
SKIP_UP="${SKIP_UP:-false}"

print_header() {
  printf "\n== %s ==\n" "$1"
}

info() {
  printf "[INFO] %s\n" "$1"
}

warn() {
  printf "[WARN] %s\n" "$1"
}

die() {
  printf "[ERROR] %s\n" "$1" >&2
  exit 1
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

random_hex() {
  local bytes="$1"

  if command_exists openssl; then
    openssl rand -hex "$bytes"
    return
  fi

  head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
}

read_env_value() {
  local file="$1"
  local key="$2"

  if [ ! -f "$file" ]; then
    return 1
  fi

  awk -F= -v key="$key" '
    $0 !~ /^[[:space:]]*#/ && $1 == key {
      value = substr($0, index($0, "=") + 1)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
      gsub(/^"|"$/, "", value)
      print value
      exit
    }
  ' "$file"
}

write_env_file() {
  local secret_key="$1"
  local api_token="$2"

  mkdir -p "$(dirname "$MAILU_ENV")"
  cat > "$MAILU_ENV" <<EOF
# Generated by scripts/mailu-setup.sh
# Keep this file private. It contains Mailu API and session secrets.

ROOT=$ROOT
VERSION=$VERSION
SECRET_KEY=$secret_key
SUBNET=$SUBNET
BIND_ADDRESS4=$BIND_ADDRESS4
BIND_ADDRESS6=

DOMAIN=$DOMAIN
HOSTNAMES=$MAIL_HOST
POSTMASTER=$POSTMASTER

TLS_FLAVOR=$TLS_FLAVOR
AUTH_RATELIMIT=$AUTH_RATELIMIT
MESSAGE_RATELIMIT=$MESSAGE_RATELIMIT

# Mail Kit needs this API enabled.
API=true
WEB_API=/api
API_TOKEN=$api_token

# Keep webmail out of the product surface for now. Mail Kit is the UI.
WEBMAIL=none
WEBDAV=none
ANTIVIRUS=clamav

# Conservative defaults for a first VPS proof.
DISABLE_STATISTICS=True
ADMIN=true
IMAP=true
POP3=false
SITENAME=Mail Kit Mail Engine
EOF
}

ensure_mailu_root() {
  local dirs=(
    "$ROOT/certs"
    "$ROOT/data"
    "$ROOT/dkim"
    "$ROOT/filter"
    "$ROOT/mail"
    "$ROOT/mailqueue"
    "$ROOT/redis"
    "$ROOT/overrides/nginx"
    "$ROOT/overrides/dovecot"
    "$ROOT/overrides/postfix"
    "$ROOT/overrides/rspamd"
  )

  if mkdir -p "${dirs[@]}" 2>/dev/null; then
    info "Mailu data directories are ready under $ROOT"
    return
  fi

  warn "Could not create $ROOT as the current user."
  warn "Run this once, then rerun the script:"
  warn "  sudo mkdir -p $ROOT/{certs,data,dkim,filter,mail,mailqueue,redis,overrides/nginx,overrides/dovecot,overrides/postfix,overrides/rspamd}"
  warn "  sudo chown -R \$(id -u):\$(id -g) $ROOT"
}

print_mailkit_env() {
  local api_token="$1"
  local mailbox_secret="$2"

  print_header "Mail Kit Server Env To Add"
  cat <<EOF
SMTP_HOST=$MAIL_HOST
SMTP_PORT=587
SMTP_SECURE=false
EMAIL=$POSTMASTER@$DOMAIN
EMAIL_PASSWORD=MAILU_MAILBOX_PASSWORD_FOR_$POSTMASTER@$DOMAIN
EMAIL_FROM="Mail Kit"

MAIL_ENGINE_MODE=mailu
MAIL_ENGINE_API_URL=https://$MAIL_HOST/api
MAIL_ENGINE_API_TOKEN=$api_token
MAIL_ENGINE_IMAP_HOST=$MAIL_HOST
MAIL_ENGINE_IMAP_PORT=993
MAIL_ENGINE_IMAP_SECURE=true
MAIL_ENGINE_SYNC_ENABLED=true
MAILBOX_SECRET_KEY=$mailbox_secret
EOF
}

print_dns() {
  print_header "DNS Records To Create"
  cat <<EOF
A     $MAIL_HOST              YOUR_VPS_IP
MX    $DOMAIN                 10 $MAIL_HOST
TXT   $DOMAIN                 "v=spf1 mx ~all"
TXT   _dmarc.$DOMAIN          "v=DMARC1; p=none; rua=mailto:$POSTMASTER@$DOMAIN"
PTR   YOUR_VPS_IP             $MAIL_HOST

DKIM will be available after the domain exists in Mailu. Check Mailu admin/API or files under:
  $ROOT/dkim
EOF
}

print_usage() {
  cat <<EOF
Usage:
  DOMAIN=example.com MAIL_HOST=mail.example.com ./scripts/mailu-setup.sh

Useful options:
  POSTMASTER=postmaster
  ROOT=/opt/mailu
  VERSION=2024.06
  MAILU_ADMIN_PASSWORD='strong password'
  SKIP_UP=true
  DRY_RUN=true

This script creates deploy/mailu.env, starts docker.maulu-setup.yml, and prints
the Mail Kit env values needed for Mailu SMTP/IMAP/API integration.
EOF
}

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  print_usage
  exit 0
fi

[ -n "$DOMAIN" ] || die "DOMAIN is required. Example: DOMAIN=example.com MAIL_HOST=mail.example.com ./scripts/mailu-setup.sh"

if [ -z "$MAIL_HOST" ]; then
  MAIL_HOST="mail.$DOMAIN"
fi

command_exists docker || die "docker is required"
docker compose version >/dev/null 2>&1 || die "docker compose is required"
[ -f "$MAILU_COMPOSE" ] || die "Mailu compose file not found: $MAILU_COMPOSE"

if [ "$DRY_RUN" != "true" ]; then
  ensure_mailu_root
fi

if [ -f "$MAILU_ENV" ]; then
  info "Using existing Mailu env: $MAILU_ENV"
else
  secret_key="$(random_hex 16)"
  api_token="$(random_hex 32)"
  write_env_file "$secret_key" "$api_token"
  info "Created Mailu env: $MAILU_ENV"
fi

api_token="$(read_env_value "$MAILU_ENV" API_TOKEN || true)"
mail_domain="$(read_env_value "$MAILU_ENV" DOMAIN || true)"
mail_hostnames="$(read_env_value "$MAILU_ENV" HOSTNAMES || true)"

if [ -z "$api_token" ]; then
  die "API_TOKEN is missing in $MAILU_ENV"
fi

if [ -z "$MAILBOX_SECRET_KEY" ]; then
  MAILBOX_SECRET_KEY="$(random_hex 32)"
fi

print_header "Mailu Setup"
info "Compose file: $MAILU_COMPOSE"
info "Env file: $MAILU_ENV"
info "Mail domain: ${mail_domain:-$DOMAIN}"
info "Mail hostnames: ${mail_hostnames:-$MAIL_HOST}"
info "Data root: $ROOT"
info "API token: set (${#api_token} chars)"

if ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq '[:.]80$|[:.]443$'; then
  warn "Something is already listening on port 80 or 443."
  warn "This standalone Mailu compose binds 80/443. Stop the conflicting service or adapt the reverse proxy layout."
fi

if [ "$SKIP_UP" = "true" ] || [ "$DRY_RUN" = "true" ]; then
  warn "Skipping docker compose up because SKIP_UP=true or DRY_RUN=true."
else
  print_header "Starting Mailu"
  MAILU_ENV_FILE="$MAILU_ENV" docker compose --env-file "$MAILU_ENV" -f "$MAILU_COMPOSE" up -d
fi

if [ -n "$MAILU_ADMIN_PASSWORD" ] && [ "$SKIP_UP" != "true" ] && [ "$DRY_RUN" != "true" ]; then
  print_header "Creating Mailu Admin"
  MAILU_ENV_FILE="$MAILU_ENV" docker compose --env-file "$MAILU_ENV" -f "$MAILU_COMPOSE" exec -T admin \
    flask mailu admin "$POSTMASTER" "$DOMAIN" "$MAILU_ADMIN_PASSWORD" || \
    warn "Admin creation command failed. It may already exist, or Mailu may still be starting."
else
  print_header "Mailu Admin Account"
  warn "No Mailu admin password was provided."
  warn "Create it later with:"
  warn "  MAILU_ADMIN_PASSWORD='strong password' DOMAIN=$DOMAIN MAIL_HOST=$MAIL_HOST ./scripts/mailu-setup.sh"
  warn "or manually:"
  warn "  MAILU_ENV_FILE=$MAILU_ENV docker compose --env-file $MAILU_ENV -f $MAILU_COMPOSE exec admin flask mailu admin $POSTMASTER $DOMAIN 'strong password'"
fi

print_mailkit_env "$api_token" "$MAILBOX_SECRET_KEY"
print_dns

print_header "Next Checks"
cat <<EOF
Run this after DNS is added and Mailu has started:

DOMAIN=$DOMAIN \\
MAIL_HOST=$MAIL_HOST \\
MAILU_ENV=$MAILU_ENV \\
MAILU_COMPOSE=$MAILU_COMPOSE \\
./scripts/check-vps-mailu.sh

Important: never delete $ROOT unless you intentionally want to wipe Mailu mailboxes, DKIM keys, and stored mail.
EOF
